FROM crystallang/crystal:1.19.1

# Based on https://github.com/emcrisostomo/fswatch/blob/master/docker/debian11/Dockerfile.in

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y git autoconf automake gettext autopoint libtool make g++ texinfo curl

ENV ROOT_HOME /root
ENV FSWATCH_BRANCH 1.18.3

WORKDIR ${ROOT_HOME}
RUN git clone https://github.com/emcrisostomo/fswatch.git

WORKDIR ${ROOT_HOME}/fswatch
RUN git checkout ${FSWATCH_BRANCH}
RUN ./autogen.sh && ./configure && make -j
RUN make install
