name: CI

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read
  
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - 
        name: Download source
        uses: actions/checkout@v4
      - 
        name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - 
        name: Fetch fswatch version
        id: fswatch-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "version=$(gh release view --repo emcrisostomo/fswatch --json tagName --jq .tagName)" >> "$GITHUB_OUTPUT"
      - 
        name: Cache libfswatch
        id: libfswatch
        uses: actions/cache@v4
        with:
          path: fswatch/target
          key: ${{ runner.os }}-${{ steps.fswatch-version.outputs.version }}-fswatch
      - 
        name: Compile libfswatch
        if: steps.libfswatch.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir fswatch/
          gh release download "${{ steps.fswatch-version.outputs.version }}" --repo emcrisostomo/fswatch --pattern 'fswatch-*.tar.gz' --output - | tar -xz -C fswatch --strip-components=1
          cd fswatch/
          ./configure
          make -j"$(getconf _NPROCESSORS_ONLN)"
          sudo make install

      - 
        name: Refresh shared library (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo ldconfig

      - 
        name: Refresh shared library (macOS)
        if: runner.os == 'macOS'
        run: |
          sudo update_dyld_shared_cache

      -
        name: Check libfswatch installation
        run: |
          pkg-config --list-all
          pkg-config --cflags --libs libfswatch

      - run: shards install

      - 
        name: Run tests (single-thread)
        id: specSingleThread
        run: crystal spec
        continue-on-error: true

      - 
        name: Run tests (multi-thread)
        id: specMultiThread
        run: crystal spec -Dpreview_mt
        continue-on-error: true

      - 
        name: Run tests (execution-context)
        id: specExecutionContext
        run: crystal spec -Dpreview_mt -Dexecution_context
        continue-on-error: true

      - 
        name: Lint
        run: crystal tool format && git diff --exit-code
        if: matrix.crystal == 'latest'

      - 
        name: CheckIfAnySpecFailed
        if: steps.specSingleThread.outcome == 'failure' || steps.specMultiThread.outcome == 'failure' || steps.specExecutionContext.outcome == 'failure'
        run: exit 1